### ISSUE TITLE
generate_tree();

### ISSUE THREAD

**Issue by 7ntys** [7ntys/Projet-C-random-sentences#1]
Créer une fonction pour générer un arbre complet

**Comment by Datharr** [comment]
> Update on 02/11/2022

**To do list on this branch :** 
@7ntys @Farroussa 

1. [ ] -Fixing the add_on_tree() function
2. [ ] -As pair as the function searching place() 
3. [ ] -Allocating space to pointer and fixing the compatibility problem between function
4. [ ] -Fixing the function children_existence especially on the if condition (approximatively line 80)

![Issue_children_existence_1](https://user-images.githubusercontent.com/61124632/199534341-a5ad726b-38c0-4e3c-bd0c-b86377ba69a4.PNG)
