### ISSUE TITLE
Generate_tree | Bug on add_on_tree function()

### ISSUE THREAD

**Issue by Datharr** [7ntys/Projet-C-random-sentences#5]
> Update on 02/11/2022 by Mathieu ROCHE

### We have a problematic issue on the add_on_tree function on the generate_tree branch, #1 
We may need to allocate dynamically the pointers instead of just generating them.
Currently I'm working on fixing this issues but I'm not at ease to work with pointer.
Notifying you on this one Julien because I might need your help @7ntys Could we go at Efrei to try to work together on this issue ?
I think it could make compatibility errors if we try to merge all branches while this issue is still present.

Don't forget to not merge Cmake File while committing on Github.

![add_on_tree](https://user-images.githubusercontent.com/61124632/199537337-f3e46284-b0bf-494e-9bdc-a9d0ce9a19e4.PNG)

**Comment by 7ntys** [comment]
### Fix of the bug
`struct node * create_struct(char value){
    p_node node1;
    node1 = (p_node)malloc(sizeof(p_node));
    node1->c = value;
    return node1;
}`
